spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mxntest?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
mybatis:
  mapper-locations: classpath*:mapper/*.xml