spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mxn_test?serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
mybatis:
  mapper-locations: classpath*:mapper/*.xml